[W5.7][W17-3]Koh Zheng Wei
nus-cs2103-AY1819S1/addressbook-level2 pull request #216
Opened 2018-09-08 19:48 UTC by Zenious

added enhancement to addressbook-level2
-Ability to see the total number of Person in address book without having to go through verbose output generated by the command `list`

2018-09-09 16:12 UTC, PakornUe requested changes
Most of the code and documentation is of good quality.

Tests are mostly adequate except the I/O one which could be more rigorous.

However, importing .* is haphazard and should be fixed.

2018-09-09 16:12 UTC, NyxF4ll commented on src/seedu/addressbook/parser/Parser.java
> +import seedu.addressbook.commands.*;
importing .* is unsafe

2018-09-09 16:12 UTC, NyxF4ll commented on src/seedu/addressbook/commands/StatsCommand.java
> +public class StatsCommand extends Command {
Shouldn't "count" be more intuitive than "stats" in this context?

2018-09-09 16:12 UTC, NyxF4ll commented on test/input.txt
> +
maybe add more test cases? (ex. clear then run stat for one more time)

2018-09-09 16:12 UTC, NyxF4ll commented on src/seedu/addressbook/commands/StatsCommand.java
> +        List<ReadOnlyPerson> allPersons = addressBook.getAllPersons().immutableListView();
This seems like a pretty good idea.

2018-09-09 16:21 UTC, PakornUe approved these changes

2018-09-09 16:22 UTC, PakornUe approved these changes

2018-09-09 16:23 UTC, PakornUe approved these changes
Ok, everything seems fine

2018-09-15 11:10 UTC, parvathy-sudhir-pillai approved these changes
Good effort on this PR @Zenious. In particular, good job on,

updating I/O tests
updating JUnit tests
keeping the PR relatively clean
updating user guide

Suggestions to improve further:
update developer guide 

As before, please close the PR after viewing comments.

2018-09-15 11:10 UTC, parvathy-sudhir-pillai commented on src/seedu/addressbook/Main.java
> +//            throw new RuntimeException(e);
Don't comment out code. Go ahead and delete all unused code. We have version control precisely to revert at any point.

2018-09-15 11:10 UTC, parvathy-sudhir-pillai commented on src/seedu/addressbook/commands/StatsCommand.java
> +
Write descriptive header comments for all public classes/methods.

2018-09-15 11:10 UTC, parvathy-sudhir-pillai commented on src/seedu/addressbook/commands/StatsCommand.java
> +
Avoid stray line breaks.

2018-09-15 11:10 UTC, parvathy-sudhir-pillai commented on test/java/seedu/addressbook/commands/StatsCommandTest.java
> +
Add descriptive comments for public classes.

2018-09-18 07:28 UTC, closed without merging