[W5.7][W16-4] Bryan Lew
nus-cs2103-AY1819S1/addressbook-level2 pull request #248
Opened 2018-09-09 15:27 UTC by blewjy

Added 'findtag' command which find persons by tag name.
Added relevant tests.
Updated user guide.

2018-09-11 03:00 UTC, ChesterSng commented
Very useful addition to the use of tags

2018-09-11 15:05 UTC, clawyq commented
Maybe the functionality of your current find tag can be generalised to a broader 'filter-like' method, allowing you to not just filter for a specific keyword in the tag field, but maybe also in the name, email and address fields as well.

Code is easy to understand and cleanly written.

2018-09-11 15:21 UTC, 99percentile commented
Might be nice if you include a command to list all tags in the address book.

But this is useful as well!

2018-09-12 07:58 UTC, 99percentile commented on src/seedu/addressbook/commands/HelpCommand.java
> -                + "\n" + DeleteCommand.MESSAGE_USAGE
Why did you do this?

2018-09-12 20:57 UTC, bqnguyen94 requested changes
Good job 👍 some changes needed.

2018-09-12 20:57 UTC, bqnguyen94 commented on src/seedu/addressbook/commands/FindTagCommand.java
> +    private List<ReadOnlyPerson> getPersonsWithNameContainingAnyKeyword(Set<String> keywords) {
I thought the method looks for `tag`?

2018-09-12 20:57 UTC, bqnguyen94 commented on src/seedu/addressbook/commands/ViewAllCommand.java
> +    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Views all (including private) details of the person "
Is this related?

2018-09-12 20:57 UTC, bqnguyen94 commented on test/java/seedu/addressbook/common/UtilsTest.java
> +    private void assertNoNull(Object... objects) { assertFalse(Utils.isAnyNull(objects)); }
This null test is not relevant to this PR, so please remove it :)

2018-09-12 20:57 UTC, bqnguyen94 commented on test/java/seedu/addressbook/parser/ParserTest.java
> +
For this command you can test executing the command as well, but for now I think this is satisfactory.

2018-12-11 11:17 UTC, closed without merging