Edit find function to not be case sensitive
nus-cs2103-AY1819S1/addressbook-level2 pull request #250
Opened 2018-09-09 15:47 UTC by clawyq

Update user guide to reflect the change in the find method

2018-09-11 02:59 UTC, ChesterSng commented
Very useful change to ab2, normally people wouldn't want to care about the upper/lower casing

2018-09-11 04:08 UTC, blewjy commented
Good and practical feature!

2018-09-11 11:03 UTC, syahiranrafi commented
Very useful feature!

2018-09-11 11:03 UTC, syahiranrafi commented
Very useful feature!

2018-09-11 15:18 UTC, 99percentile commented
Nice!! Now we do not need to care about caps when finding things

2018-09-12 20:49 UTC, bqnguyen94 requested changes
Good job 👍 just a minor change needed.

2018-09-12 20:49 UTC, bqnguyen94 commented on src/seedu/addressbook/commands/FindCommand.java
> +        for (String word : keywords) {
FYI: There's a neater way to do this. [See here.](https://dzone.com/articles/how-to-use-map-filter-collect-of-stream-in-java-8)

2018-09-12 20:49 UTC, bqnguyen94 commented on test/java/seedu/addressbook/commands/FindCommandTest.java
> +        assertFindCommandBehavior(new String[]{"AMy", "AmY"}, Arrays.asList(td.amy));
I think `AMy` and `AmY` are not repeated keywords?

2020-09-28 02:47 UTC, closed without merging