[W5.7][F10-4] ONG MING XIAN
nus-cs2103-AY1819S1/addressbook-level2 pull request #328
Opened 2018-09-11 10:58 UTC by m4dkip

Add sort command to sort the address book in alphabetical order.

2018-09-11 11:23 UTC, yican95 commented
Good job. Can try to add JUnit test for sort command

2018-09-13 11:41 UTC, azhikai requested changes

2018-09-13 11:41 UTC, AZhiKai commented on src/seedu/addressbook/commands/SortCommand.java
> +
This extra empty line can be removed. 😄 
Other than that, could improve by adding unit test for your sort command.

2018-09-13 13:33 UTC, HyperionNKJ commented
Great job! You may want to commit more often. It'll help you keep track of your changes :)

2018-09-13 15:37 UTC, rebstan97 commented
Good job! Can commit every time you make minor changes so it is easier to revert back in case there's a need.

2018-09-15 02:07 UTC, dalessr approved these changes
@m4dkip Well done for the `sort` command 👍 Remember to update user guide and add JUnit tests for the new feature.

Please close the PR after looking at the comments below.

2018-09-15 02:07 UTC, dalessr commented on src/seedu/addressbook/data/AddressBook.java
> +     *
Empty line is not necessary here.

2018-09-15 02:07 UTC, dalessr commented on src/seedu/addressbook/data/person/UniquePersonList.java
> +                return o1.toString().compareTo(o2.toString());
Are you trying to sort by name or other attributes? I cannot get what you are comparing. If you just want to sort by name (as default), why not using `Collections.sort()` directly?

2018-09-15 12:05 UTC, closed without merging