[W5.7][F10-4] Lee Yi Can
nus-cs2103-AY1819S1/addressbook-level2 pull request #330
Opened 2018-09-11 11:34 UTC by yican95

Ignore the first commit. Forgot to branch for the week 4 LOs.

2018-09-11 11:40 UTC, m4dkip commented
Good job. Proper encapsulation used and user guide updated neatly.

2018-09-11 12:07 UTC, AZhiKai commented
Good use of commit to keep track of small changes. 
New feature added along with its unit test.

2018-09-13 13:36 UTC, HyperionNKJ commented
Good job! User guide updated well. You may want to extend sort to tags :)

2018-09-13 15:36 UTC, rebstan97 commented
Nicely done! All tests updated neatly.

2018-09-15 02:16 UTC, dalessr requested changes
@yican95 Well done for the sort command 👍 This PR is rejected as it is not a clean PR.

Please close the PR after looking at the comments below.

2018-09-15 02:16 UTC, dalessr commented on docs/UserGuide.adoc
> +=== Sorting all entries: `sort`
Font size different from the others (as you are using `===`)?

2018-09-15 02:16 UTC, dalessr commented on src/seedu/addressbook/data/AddressBook.java
> +    public void sort() { allPersons.sort(); }
Coding standard violation here. Split into multiple lines.

2018-09-15 02:16 UTC, dalessr commented on test/java/seedu/addressbook/commands/SortCommandTest.java
> +import static org.junit.Assert.*;
Coding standard violation here. Should specify all the classes used in this file.

2018-09-15 02:16 UTC, dalessr commented on test/java/seedu/addressbook/commands/SortCommandTest.java
> +import org.junit.Test;
Split the import into multiple groups as the packages are imported from different sources.

2018-09-15 02:16 UTC, dalessr commented on test/java/seedu/addressbook/commands/SortCommandTest.java
> +     * @return
Description missing here. What does this method return?

2018-09-15 02:16 UTC, dalessr commented on test/java/seedu/addressbook/commands/SortCommandTest.java
> +}
New line is required at the end of each file

2018-09-15 12:29 UTC, closed without merging