[W5.7][W16-1]Kok Yuan
nus-cs2103-AY1819S1/addressbook-level2 pull request #341
Opened 2018-09-11 14:01 UTC by EatOrBeEaten

2018-09-11 14:54 UTC, javenseow commented
Could have included the sort in the user guide. Good work nonetheless.

2018-09-11 15:23 UTC, GilgameshTC commented
I think adding empty lines in between each command message displayed really helps with readability. Shame it was removed later on!

2018-09-11 15:27 UTC, kengwoon commented
Would be better with more test cases. But still good job.

2018-09-11 16:00 UTC, ericyjw commented
Good job! Comments can be added to the method to explain what the method do

2018-09-12 19:55 UTC, bqnguyen94 requested changes
Good job 👍 just some minor changes needed. Also, for this `sort` command you can add more rigorous tests to check if the internal list is really sorted or not, but this is satisfactory for now.

2018-09-12 19:55 UTC, bqnguyen94 commented on src/seedu/addressbook/parser/Parser.java
> +import seedu.addressbook.commands.*;
These style changes are not really relevant to the main purpose of the PR

2018-09-12 19:55 UTC, bqnguyen94 commented on test/java/seedu/addressbook/parser/ParserTest.java
> +import seedu.addressbook.commands.*;
Same here

2018-09-24 09:07 UTC, closed without merging