[W5.7][W16-1]Javen Seow Yu Bin
nus-cs2103-AY1819S1/addressbook-level2 pull request #353
Opened 2018-09-11 15:36 UTC by javenseow

Added contain command

2018-09-11 15:51 UTC, kengwoon commented
Can add more test cases, but other than that, all is good.

2018-09-11 15:55 UTC, GilgameshTC commented
It would be better if the changes were done incrementally, but great job none-the-less!

2018-09-11 15:58 UTC, ericyjw commented
Good job! However, you could have added comments before the methods!

2018-09-12 08:03 UTC, kengwoon approved these changes

2018-09-12 08:03 UTC, kengwoon commented on src/seedu/addressbook/commands/ContainCommand.java
> +        boolean personFound = checkDuplicate(name);
can name variable as isPersonFound

2018-09-12 19:26 UTC, bqnguyen94 requested changes
Almost there 👍

2018-09-12 19:26 UTC, bqnguyen94 commented on src/seedu/addressbook/parser/Parser.java
> +    private Command prepareContain(String args) {
Would be nice if this function has explanatory comments as well, see the `prepareAdd` function below :)

2018-09-12 19:26 UTC, bqnguyen94 commented on src/seedu/addressbook/parser/Parser.java
> +import seedu.addressbook.commands.*;
These style changes are not really relevant to the purpose of this PR which is adding the `contain` command.

2018-09-12 19:26 UTC, bqnguyen94 commented on test/expected.txt
> +|| contain: Searches the address book with given name
How about an usage example as well? :)

2018-09-12 19:26 UTC, bqnguyen94 commented on test/java/seedu/addressbook/commands/ContainCommandTest.java
> +    private void assertContainSuccessful(String name, AddressBook addressbook, boolean contained) throws IllegalValueException {
Nitpick: leave a line between functions to separate them.

2018-09-12 19:26 UTC, bqnguyen94 commented on test/java/seedu/addressbook/parser/ParserTest.java
> +import seedu.addressbook.commands.*;
These changes are also not really relevant?

2018-09-12 19:36 UTC, bqnguyen94 requested changes
Pls update the user guide as well

2018-09-14 06:49 UTC, javenseow commented on test/expected.txt
> +|| contain: Searches the address book with given name
Added an example!

2018-09-15 07:24 UTC, bqnguyen94 approved these changes
Good job 👍 you can close the PR now.

2018-09-15 07:24 UTC, bqnguyen94 commented on test/java/seedu/addressbook/parser/ParserTest.java
> +
This is not needed. Normally we only separate imports that are from different parties.

2018-09-21 04:36 UTC, closed without merging